### ISSUE TITLE
Can't easily open job ads in new tab

### ISSUE THREAD

**Issue by arp242** [golang-cafe/golang.cafe#1]
To open job ads in new tab from the home page I need to expand the job, scroll to the bottom of it, middle-click "link", and I've got it in a new tab.

Expected behaviour would be to just middle-click the job title, so I can easily open several job postings in one go. This would also improve the experience without JavaScript ([applicable comment I made somewhere else a few days ago](https://lobste.rs/s/qxetqn/everyone_has_javascript_right#c_23kmel)).

This is probably as easy as just [adding the `href=".."` here](https://github.com/golang-cafe/golang.cafe/blob/d1ed054c8d7558695ddfa217e9967eb766a57786/static/views/landing.html#L156) and making sure the JavaScript calls `event.preventDefault()`, if it doesn't already.

**Comment by 0x13a** [comment]
There are a variety of reasons why the jobs are displayed/expanded on the main search page
The main reason for having it this way is SEO, it tremendously improve word count for each search page.
I agree at the moment the logic to expand the job description is a bit fiddly but I'm working around it to make it more usable.

I'll close this issue as it's all related to job expand/collapse feature.
