### ISSUE TITLE
Deployment of Dockerized Postgres and Golang to VM

### ISSUE THREAD

**Issue by milimyname** [golang-cafe/golang.cafe#129]
Hi everyone.

I wonder if it is alright to ask a question regarding of deployment golang cafe oss?

I got a VM and I wanna deploy together the dockerized postgres and golang app using docker compose. Has anyone done it or what would you recommend me to do instead? When I tried to deploy seperately, I got some issues regarding of connection to the postgres even though I psqled it successfully. 

If I deploy them separately, I believe I need to take care of db persistent volume?

**Comment by ghost** [comment]
yes you need to have a persistent volume is you intend to use a dockerised version of postgres. another option is to use postgres as a service from the many providers out there
