### ISSUE TITLE
Selecting text closes a job posting

### ISSUE THREAD

**Issue by arp242** [golang-cafe/golang.cafe#2]
If I expand a job posting on the home page and select some text from it, the detailed text collapses again.

This also happens when you click just outside of the "link" or "Apply" buttons, by the way. In general, I find the entire UX of "click anywhere in the text for an action" a bit confusing to be honest.

Firefox 70 on Linux

**Comment by 0x13a** [comment]
Closing this one as it's related to #3 - Let's continue the discussion around job expand/collapse on that issue.
