### ISSUE TITLE
Collapsing the job ads is extremely disorientating

### ISSUE THREAD

**Issue by arp242** [golang-cafe/golang.cafe#3]
Scrolling down and then closing a job posting is actually really disorientating; let's say my view looks like this:
```
  1. Job ad
^ 2. Job ad
| 3. Job ad
|    Expanded text ..
|    Expanded text ..
v    Expanded text ..
     Expanded text ..
     Expanded text ..
  4. Job ad
  5. Job ad
  6. Job ad
  7. Job ad
  8. Job ad
  9. Job ad
```

The thing on the left represents scrollbar and my browser's viewport. I scrolled down to "job ad 3" and am reading the description. I scroll down and decide I don't want it so collapse it, and now I have:

```
  1. Job ad
  2. Job ad
  3. Job ad
  4. Job ad
^ 5. Job ad
| 6. Job ad
| 7. Job ad
| 8. Job ad
v 9. Job ad
```

And I completely missed job posting 4. In reality, it's often more than just one listing. I'm having a real hard time to continue from where I left off.

Firefox 70 on Linux

**Comment by 0x13a** [comment]
you are right the whole job expansion logic has a really poor UX

**Comment by 0x13a** [comment]
I've quickly added a workaround https://github.com/golang-cafe/golang.cafe/commit/f1cd2d1536ba21417f3c218b1d9d53a02d8534d8

But this probably needs more attention and a better solution

**Comment by pizzatarian** [comment]
This should be fixed as now the collapse/expand is only on the title of the job post. That would mean you need to go back up to the top of job 3 to collapse it and you would not miss any other job. I'm thinking whether it would make sense to expand/collpase the job description this as a floating window in page and whether would make the UX better that what it is right now. Please let me know. I'm closing this issue for now as the original behaviour as been fixed. Thx!

**Comment by arp242** [comment]
Seems much better now, thanks! :+1: 

> I'm thinking whether it would make sense to expand/collpase the job description this as a floating window in page and whether would make the UX better that what it is right now.

I'm not sure; I personally rather like the fancy no-frills UI it has now, but that's just a personal taste.

Another very small issue (possible bikeshed), but I'd change "Visit link" to "Permalink" or something, now it's not obvious that it's a link to golang.cafe permalink or the company's home page or something.

**Comment by arp242** [comment]
Also, and I hope you don't mind me plugging my own tool here, in response to [Removing JS trackers From Golang Cafe](https://golang.cafe/changelog/removing-js-trackers.html), I'm actually working on a better solution for that: https://github.com/zgoat/goatcounter, in case you're interested 😅

**Comment by pizzatarian** [comment]
@arp242 thanks for sharing! I'll have a look shortly and feedback - seems good so far!
