### ISSUE TITLE
Error: When creating a new account with same email there's no clear error message

### ISSUE THREAD

**Issue by jeanlucaslima** [golang-cafe/golang.cafe#9]
When signing up, if someone by mistake use the same account as someone else or if they already have an account it is impossible to know what happened, the site just gives an alert saying error happened. It should display that someone is already using that email and should login instead of signing up.

**Comment by pizzatarian** [comment]
thanks for reporting this @jeanlucaslima  - that's right - i am currently looking to remove some of the sign on logic that uses a token to know what the next step is. it would be good to have the auth endpoint to automatically detect if a user exists, if needs to be created or if it's an admin. the logic is all pretty much in the auth handler

**Comment by pizzatarian** [comment]
@jeanlucaslima i have pushed a fix for this please see this commit https://github.com/golang-cafe/golang.cafe/commit/b814f98582cf84506c9db528c7cb7922e7b94b17 - i will be creating a refactoring ticket to remove the auth steps so it's more clear when logging in etc

**Comment by pizzatarian** [comment]
#10
